---
Aim:Creating pathology annotation plots on spots focusing on the fibrous and adipose stroma for figure 1 panels C, F, I, L
---

```{r} 
# Load packages 
library(semla)
library(ggplot2)
library(tidyverse)
library(dplyr)
```

Load vis_mod object 
```{r}
# Load data (Seurat with correct image size and pathology annotations included)
vis_mod <- readRDS(file = paste0("/Users/leirealonso/Documents/ST/Project_Garvan_institute/Human_Breast_Cancer_Atlas/hard_vs_soft_cover/for_manuscripts/analysis/output/rds_objects/", "vis_mod_anno.rds"))
```

Trying mapping path annotations on tissue sections
```{r}
annotation_colors <- c('#ffe119', '#46f0f0',"#eeeeee")
# Here we use the & operator from the patchwork R package to add a theme
# You can find more details in the 'advanced' tutorial

MapLabels(vis_mod, column_name = "Stroma_Anno", colors = annotation_colors, pt_size = 1.3, pt_alpha = 0.5, section_number = 8, ncol = 1) & #Section_number 8 corresponds to the Patient 4 prepared with the STAY method. 
  theme(legend.position = "right")

#The same can be done with the Epithelial_Anno and Immune_Anno. The immune and epithelial layers stored in the metadata in the Seurat object. 
#p <- MapLabels(vis_mod, column_name = "Immune_Anno", pt_size = 1.3, pt_alpha = 0.5, section_number = 8, ncol = 1) &
  #theme(legend.position = "right")
#print(p)
```

```{r}
# Here we use the & operator from the patchwork R package to add a theme
# You can find more details in the 'advanced' tutorial
MapLabels(vis_mod, column_name = "Stroma_Anno", pt_size = 1.3, pt_alpha = 0.5, colors = annotation_colors, section_number = 7, ncol = 1) &
  theme(legend.position = "right")
```

```{r}
annotation_colors <- c('#ffe119', '#46f0f0',"#eeeeee")
# Here we use the & operator from the patchwork R package to add a theme
# You can find more details in the 'advanced' tutorial
MapLabels(vis_mod, column_name = "Stroma_Anno", pt_size = 1.3, pt_alpha = 0.5, colors = annotation_colors, section_number = 1, ncol = 1) &
  theme(legend.position = "right")
```

```{r}
annotation_colors <- c('#ffe119', '#46f0f0',"#eeeeee")
# Here we use the & operator from the patchwork R package to add a theme
# You can find more details in the 'advanced' tutorial
MapLabels(vis_mod, column_name = "Stroma_Anno", pt_size = 1.3, pt_alpha = 0.5, colors = annotation_colors, section_number = 2, ncol = 1) &
  theme(legend.position = "right")
```

```{r}
annotation_colors <- c('#ffe119', '#46f0f0',"#eeeeee")
# Here we use the & operator from the patchwork R package to add a theme
# You can find more details in the 'advanced' tutorial
MapLabels(vis_mod, column_name = "Stroma_Anno", colors = annotation_colors, pt_size = 2, pt_alpha = 0.5, section_number = 3, ncol = 1) &
  theme(legend.position = "right")
```

```{r}
annotation_colors <- c('#ffe119', '#46f0f0',"#eeeeee")
# Here we use the & operator from the patchwork R package to add a theme
# You can find more details in the 'advanced' tutorial
MapLabels(vis_mod, column_name = "Stroma_Anno", pt_size = 2, pt_alpha = 0.5, colors = annotation_colors, section_number = 4, ncol = 1) &
  theme(legend.position = "right")
```
```{r}
annotation_colors <- c('#ffe119', '#46f0f0',"#eeeeee")
# Here we use the & operator from the patchwork R package to add a theme
# You can find more details in the 'advanced' tutorial
MapLabels(vis_mod, column_name = "Stroma_Anno", pt_size = 2, pt_alpha = 0.5, colors = annotation_colors, section_number = 5, ncol = 1) &
  theme(legend.position = "right")
```

```{r}
annotation_colors <- c('#ffe119', '#46f0f0',"#eeeeee")
# Here we use the & operator from the patchwork R package to add a theme
# You can find more details in the 'advanced' tutorial
MapLabels(vis_mod, column_name = "Stroma_Anno", pt_size = 2, pt_alpha = 0.5, colors = annotation_colors, section_number = 6, ncol = 1) &
  theme(legend.position = "right")
```
Let's see how the epithelial and immune annotation looks like 

```{r, width = 15, height = 8}
# Here we use the & operator from the patchwork R package to add a theme
# You can find more details in the 'advanced' tutorial
MapLabels(vis_mod, column_name = "Epithelial_Anno", ncol = 4) &
  theme(legend.position = "right")
```

```{r, width = 15, height = 8}
# Here we use the & operator from the patchwork R package to add a theme
# You can find more details in the 'advanced' tutorial
MapLabels(vis_mod, column_name = "Immune_Anno", ncol = 4) &
  theme(legend.position = "right")
```

```{r}
# Define a named vector linking section_id to method
method_map <- c("4335_3D_R1L_s1" = "hard_cover", 
                "4335_3D_R1L_s2" = "soft_cover",
                "4393_2H_R1S" = "soft_cover", 
                "4393_2H_R1S_rep" = "hard_cover", 
                "4419_3F_R1S" = "soft_cover", 
                "4419_3F_R1S_rep" = "hard_cover",
                "4515_4L_R1L" = "soft_cover",
                "4515_4L_R1L_rep" = "hard_cover")
                
# Assign method dynamically based on section_id in vis_mod
vis_mod@meta.data$method <- method_map[vis_mod@meta.data$sample_id]

# Check if order is consistent
table(vis_mod@meta.data$method)
table(vis_mod@meta.data$sample_id, vis_mod@meta.data$method)

# Use the following code to reorder the section_id


vis_mod@meta.data$sample_id <- factor(vis_mod@meta.data$sample_id, 
                                       levels = c("4335_3D_R1L_s1", 
                                                  "4335_3D_R1L_s2", 
                                                  "4393_2H_R1S_rep", 
                                                  "4393_2H_R1S", 
                                                  "4419_3F_R1S_rep", 
                                                  "4419_3F_R1S", 
                                                  "4515_4L_R1L_rep", 
                                                  "4515_4L_R1L"))
# Check if order is consistent
table(vis_mod@meta.data$sample_id, vis_mod@meta.data$method)
```

#### Save vis_mod object with annotations and method

```{r}
saveRDS(vis_mod,
        file = paste0("/Users/leirealonso/Documents/ST/Project_Garvan_institute/Human_Breast_Cancer_Atlas/hard_vs_soft_cover/for_manuscripts/analysis/output/rds_objects/", "vis_mod_anno.rds"))
```

